SET TIME ZONE 'UTC';

CREATE TABLE client(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(200) NOT NULL CHECK (LENGTH(NAME) >= 3)
);

CREATE TABLE planet(
    ID  VARCHAR NOT NULL CHECK (ID = UPPER(ID) AND ID REGEXP '^[A-Z0-9]+$'),
    NAME VARCHAR(500) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE ticket(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    CLIENT_ID INT ,
    FROM_PLANET_ID VARCHAR(100),
    TO_PLANET_ID VARCHAR(100),
    FOREIGN KEY (CLIENT_ID) references client(ID),
    FOREIGN KEY (FROM_PLANET_ID) references planet(ID),
    FOREIGN KEY (TO_PLANET_ID) references planet(ID)
);
